version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: rds-server-test-03.ctrvlqjj9icq.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: yourpassword
      WORDPRESS_DB_NAME: nome_do_seu_banco
    volumes:
      - /efs/wordpress:/var/www/html/wp-content

  
